### ISSUE TITLE
Restart command for devgroup admins

### ISSUE THREAD

**Issue by FRQDO** [Eisfunke/Secret-Hitler-Telegram#36]
Desired behavior:

On /restart, the bot checks if the command was posted in the devgroup and if the poster is an admin there.
Then, if there is no game running, the bot is reloaded with the most recent code base.

If a game is running, the bot will inform about this (with a link to any group(s) with an active game) and suggest to either `/restart hard` (immediately cancelling the running game(s)) or `/reset soft` to automatically restart the bot as soon as the game(s) is/are finished.

If multiple games are in progress, it might be worth considering to add a “maintenance flag” for the bot that is cleared on restart and prevents new games from being created while it is set.

**Comment by Eisfunke** [comment]
Restart is working now. A check for running games has yet to be implemented.
